### ISSUE TITLE
[Kodi-Matrix] URLQuick - issue

### ISSUE THREAD

**Issue by wwark** [willforde/urlquick#13]
Hi @willforde,
Thanks for your work to port codequick on Kodi Matrix !

I have this issue below.
This code works without issue on Kodi Leai (18) but raised this issue on Kodi Matrix (19)

**return hashlib.sha1(b''.join((data, req.body or b''))).hexdigest()
                                                   TypeError: sequence item 1: expected a bytes-like object, str found**

> 2021-02-27 11:32:02.408 T:4142    ERROR <general>: [Catch-up-TV-&-More.support] sequence item 1: expected a bytes-like object, str found
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py", line 550, in get_live_url
                                                       resp2 = urlquick.post(
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 505, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 482, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 436, in request
                                                       response = super(Session, self).request(*args, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 445, in send
                                                       return super(Session, self).send(request, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 349, in send
                                                       urlhash = hash_url(request)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 203, in hash_url
                                                       return hashlib.sha1(b''.join((data, req.body or b''))).hexdigest()
                                                   TypeError: sequence item 1: expected a bytes-like object, str found

Thanks for your help !
@sy6sy2

**Comment by willforde** [comment]
I have that issue fixed. I can push the change to Kodi now. But I was thinking of waiting a day before submitting it in case a new issue pops up. You OK with that.

**Comment by wwark** [comment]
Thank a lot for the quick fix !
No problem you can push the fix when you are ready for it.
I will test in the next days all the cases used on CUTV&More so maybe new issue will be submitted.
:+1:

**Comment by wwark** [comment]
Hi @willforde,
How are you ?
I finished my tests on my side and don't see any new issue related to CodeQuick or Urlquick.
Thanks a lot for the next release !

**Comment by willforde** [comment]
I have submitted the pull requests to Kodi. Shouldn't take too long to be approved.

**Comment by wwark** [comment]
Thanks a lot @willforde :+1:
