### ISSUE TITLE
Encoding - Japanese website

### ISSUE THREAD

**Issue by wwark** [willforde/urlquick#5]
Hi @willforde,

Happy New Year !

I have a new issue related to this website "http://qvc.jp/cont/live/Main". Urlquick don't seem to know the encoding of this page "LookupError: unknown encoding: windows-31j"

Thanks for your help !

> FATAL: [Catch-up-TV-&-More.support] unknown encoding: windows-31j
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 282, in 
run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 361, in live_bridg
e
                                                return item_module.live_entry(plugin, item_id, item_dict)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/qvc.py",
 line 53, in live_entry
                                                return get_live_url(plugin, item_id, item_id.upper(), item_dict)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/qvc.py",
 line 79, in get_live_url
                                                r'cdn-live1\.qvc\.jp(.*?)\'').findall(resp.text)[0]
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/urlquick.py", line 250, in __get__
                                                value = instance.__dict__[self.__name__] = self.__get(instance)
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1186, in text
                                                return self.content.decode(self.encoding)
                                            LookupError: unknown encoding: windows-31j

**Comment by willforde** [comment]
Hi. The site is incorrectly reporting the encoding in the response headers. It actually uses `shift_jis`.
A work around is to set `resp.encoding = "shift_jis"` before you call `resp.text`.

I will have a look to see how `requests` handles content encoding detection, and try to improve how `urlquick` detection works.

Thanks.

**Comment by wwark** [comment]
Thank you !
